sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - redis-server
install:
  - pip install flake8 -r requirements.txt
script:
  - flake8 --max-line-length=150 --ignore=E402,F401 --exclude=venv .
  - nosetests
