sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
services:
  - redis-server
install:
  - pip install flake8 -r requirements.txt
script:
  - flake8 .
  - nosetests --processes=-1 --process-timeout=300
